---

# Default ASCII art shown at the beginning of the motd
motd_ascii_art: "     _              _ _     _\n    / \\   _ __  ___(_) |__ | | ___\n   / _ \\ | '_ \\/ __| | '_ \\| |/ _ \\\n  / ___ \\| | | \\__ \\ | |_) | |  __/\n /_/   \\_\\_| |_|___/_|_.__/|_|\\___|\n"

# Default information to show under the ASCII art
motd_info:
  - " Latest Config: ": "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
  - " FQDN:          ": "{{ ansible_fqdn }}"
  - " Distro:        ": "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
  - " Virtual:       ": "{{ 'YES' if ansible_virtualization_role == 'guest' else 'NO' }}\n"
  - " CPUs:          ": "{{ ansible_processor_vcpus }}"
  - " RAM:           ": "{{ (ansible_memtotal_mb / 1000) | round(1) }}GB"
